import img1 from "../../src/assets/sliderImg1.jpg";
import img2 from "../../src/assets/sliderImg2.jpg";
import img3 from "../../src/assets/sliderImg3.jpg";

import img4 from "../../src/assets/photogalarry1.jpg";
import img5 from "../../src/assets/photogalarry2.jpg";
import img6 from "../../src/assets/photogalarry3.jpg";
import img7 from "../../src/assets/photogalarry4.jpg";
import img8 from "../../src/assets/insights.png";

import { INDUSTRYINSIGHTS, PRESSRELEASES,LATEXTNEWS } from "../Types";




export const latestNews: LATEXTNEWS[]=[
  
      {img:"https://gitex.com/Uploads//Posts/news/dubai-rts.jpg",
      content:"Press Release",
      discription:" GITEX GLOBAL, Expand North Star 2023 centre worlds attention on booming AI economy "        
       },
       {img:"https://gitex.com/Uploads//Posts/Futuremobility/pressreleasegermany.jpg",
       content:"Industry News",
       discription:"GITEX catalyses global tech ecosystem expansion with momentous European launch in world’s most dominant tech economy"        
        },
        {img:"https://gitex.com/Uploads//Posts/news/enspress.jpg",
        content:"Press Release",
        discription:" GITEX GLOBAL, Expand North Star 2023 centre worlds attention on booming AI economy "        
         },
         {img:"https://gitex.com/Uploads//Posts/news/binancefutureblock.png",
         content:"Industry News",
         discription:"GITEX catalyses global tech ecosystem expansion with momentous European launch in world’s most dominant tech economy"        
          },
          {img:"https://gitex.com/Uploads//Posts/news/STEVEHOLDEN.jpg",
          content:"Press Release",
          discription:" GITEX GLOBAL, Expand North Star 2023 centre worlds attention on booming AI economy "        
           },
           {img:"https://gitex.com/Uploads//Posts/news/18.jpg",
           content:"Industry News",
           discription:"GITEX catalyses global tech ecosystem expansion with momentous European launch in world’s most dominant tech economy"        
            },
            {img:"https://gitex.com/Uploads//Posts/news/ciscosplunk.jpg",
          content:"Press Release",
          discription:" GITEX GLOBAL, Expand North Star 2023 centre worlds attention on booming AI economy "        
           },
           {img:"https://gitex.com/Uploads//Posts/news/attendeeinterview.jpg",
           content:"Industry News",
           discription:"GITEX catalyses global tech ecosystem expansion with momentous European launch in world’s most dominant tech economy"        
            },
            {img:"https://gitex.com/Uploads//Posts/news/amazonrainforest.jpg",
          content:"Press Release",
          discription:" GITEX GLOBAL, Expand North Star 2023 centre worlds attention on booming AI economy "        
           },
  
]

export const gallery: string[] = [img1, img2, img3, img4, img5, img6, img7];

export const industryInsights: INDUSTRYINSIGHTS[] = [
  {
    img: img8,
    discription: "NEUROMORPHIC AI: LEAPFROG OPPORTUNITY FOR MIDDLE EAST",
  },
  {
    img: img8,
    discription: "NEUROMORPHIC AI: LEAPFROG OPPORTUNITY FOR MIDDLE EAST",
  },
  {
    img: img8,
    discription: "NEUROMORPHIC AI: LEAPFROG OPPORTUNITY FOR MIDDLE EAST",
  },
];

export const pressReleasereverse: PRESSRELEASES[] = [
  {
    img: "https://gitex.com/media/Uploads//Posts/Expand%20North%20Star%20will%20be%20held%20from%2010-12%20May%202023%20at%20the%20Dubai%20World%20Trade%20Centre.jpeg",
    date: "06/12/2022",
    discription:
      "GITEX GLOBAL 2022 takes over Dubai with record capacity, accelerating world’s digital economy innovations enthral audiences at GITEX GLOBAL 2022",
  },
  {
    img: "https://gitex.com/media/Uploads//Posts/GITEX%20GLOBAL%202022%20Day%201%20-%20HH%20Sheikh%20Maktoum%20opens%20worlds%20largest%20tech%20show.jpg",
    date: "06/12/2022",
    discription: "Web 3.0 innovations enthral audiences at GITEX GLOBAL 2022",
  },

  {
    img: "https://gitex.com/media/Uploads//Posts/GITEX%20GLOBAL%202023/Cybersecurity%20in%20the%20Spotlight%20as%20GITEX%20GLOBAL%202023%20Opens.jpg",
    date: "06/12/2022",
    discription:
      "Record-breaking GITEX GLOBAL 2022 generates AED2.6 billion in total economic output",
  },
  {
    img: "https://gitex.com/media/Uploads//Posts/Xverse_GITEX%20Global%202023.jpg",
    date: "06/12/2022",
    discription:
      "GITEX GLOBAL 2022 takes over Dubai with record capacity, accelerating world’s digital economy innovations enthral audiences at GITEX GLOBAL 2022",
  },
  {
    img: "https://gitex.com/media/Uploads//Posts/Web%203.0%20innovations%20enthral%20audiences%20at%20GITEX%20GLOBAL%202022.jpg",
    date: "06/12/2022",
    discription: "Web 3.0 innovations enthral audiences at GITEX GLOBAL 2022",
  },
  {
    img: "https://gitex.com/media/Uploads//Posts/press-release-dwtc/GITEX%20Global.jpg",
    date: "06/12/2022",
    discription:
      "Record-breaking GITEX GLOBAL 2022 generates AED2.6 billion in total economic output",
  },
];

export const pressRelease: PRESSRELEASES[] = [
  {
    img: "https://gitex.com/media/Uploads//Posts/press-release-dwtc/GITEX%20Global.jpg",
    date: "06/12/2022",
    discription:
      "Record-breaking GITEX GLOBAL 2022 generates AED2.6 billion in total economic output",
  },
  {
    img: "https://gitex.com/media/Uploads//Posts/Web%203.0%20innovations%20enthral%20audiences%20at%20GITEX%20GLOBAL%202022.jpg",
    date: "06/12/2022",
    discription: "Web 3.0 innovations enthral audiences at GITEX GLOBAL 2022",
  },
  {
    img: "https://gitex.com/media/Uploads//Posts/Xverse_GITEX%20Global%202023.jpg",
    date: "06/12/2022",
    discription:
      "GITEX GLOBAL 2022 takes over Dubai with record capacity, accelerating world’s digital economy innovations enthral audiences at GITEX GLOBAL 2022",
  },
  {
    img: "https://gitex.com/media/Uploads//Posts/GITEX%20GLOBAL%202023/Cybersecurity%20in%20the%20Spotlight%20as%20GITEX%20GLOBAL%202023%20Opens.jpg",
    date: "06/12/2022",
    discription:
      "Record-breaking GITEX GLOBAL 2022 generates AED2.6 billion in total economic output",
  },
  {
    img: "https://gitex.com/media/Uploads//Posts/GITEX%20GLOBAL%202022%20Day%201%20-%20HH%20Sheikh%20Maktoum%20opens%20worlds%20largest%20tech%20show.jpg",
    date: "06/12/2022",
    discription: "Web 3.0 innovations enthral audiences at GITEX GLOBAL 2022",
  },
  {
    img: "https://gitex.com/media/Uploads//Posts/Expand%20North%20Star%20will%20be%20held%20from%2010-12%20May%202023%20at%20the%20Dubai%20World%20Trade%20Centre.jpeg",
    date: "06/12/2022",
    discription:
      "GITEX GLOBAL 2022 takes over Dubai with record capacity, accelerating world’s digital economy innovations enthral audiences at GITEX GLOBAL 2022",
  },
];

export const countries: string[] = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo (Congo-Brazzaville)",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia (Czech Republic)",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Holy See",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar (formerly Burma)",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia (formerly Macedonia)",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine State",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States of America",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const nationalities = [
  "Afghan",
  "Albanian",
  "Algerian",
  "Andorran",
  "Angolan",
  "Antiguan and Barbudan",
  "Argentinian",
  "Armenian",
  "Australian",
  "Austrian",
  "Azerbaijani",
  "Bahamian",
  "Bahraini",
  "Bangladeshi",
  "Barbadian",
  "Belarusian",
  "Belgian",
  "Belizean",
  "Beninese",
  "Bhutanese",
  "Bolivian",
  "Bosnian",
  "Brazilian",
  "British",
  "Bruneian",
  "Bulgarian",
  "Burkinabe",
  "Burundian",
  "Cambodian",
  "Cameroonian",
  "Canadian",
  "Cape Verdean",
  "Central African",
  "Chadian",
  "Chilean",
  "Chinese",
  "Colombian",
  "Comoran",
  "Congolese",
  "Costa Rican",
  "Croatian",
  "Cuban",
  "Cypriot",
  "Czech",
  "Danish",
  "Djiboutian",
  "Dominican",
  "Dominican (from Dominica)",
  "Dutch",
  "Ecuadorian",
  "Egyptian",
  "Emirati",
  "Equatorial Guinean",
  "Eritrean",
  "Estonian",
  "Eswatini",
  "Ethiopian",
  "Fijian",
  "Finnish",
  "French",
  "Gabonese",
  "Gambian",
  "Georgian",
  "German",
  "Ghanaian",
  "Greek",
  "Grenadian",
  "Guatemalan",
  "Guinean",
  "Guyanese",
  "Haitian",
  "Honduran",
  "Hungarian",
  "Icelandic",
  "Indian",
  "Indonesian",
  "Iranian",
  "Iraqi",
  "Irish",
  "Israeli",
  "Italian",
  "Ivorian",
  "Jamaican",
  "Japanese",
  "Jordanian",
  "Kazakhstani",
  "Kenyan",
  "Kuwaiti",
  "Kyrgyz",
  "Laotian",
  "Latvian",
  "Lebanese",
  "Liberian",
  "Libyan",
  "Liechtensteiner",
  "Lithuanian",
  "Luxembourger",
  "Malagasy",
  "Malawian",
  "Malaysian",
  "Maldivian",
  "Malian",
  "Maltese",
  "Mauritanian",
  "Mauritian",
  "Mexican",
  "Micronesian",
  "Moldovan",
  "Monacan",
  "Mongolian",
  "Montenegrin",
  "Moroccan",
  "Mosotho",
  "Motswana",
  "Mozambican",
  "Namibian",
  "Nauruan",
  "Nepalese",
  "New Zealander",
  "Nicaraguan",
  "Nigerian",
  "Nigerien",
  "North Korean",
  "North Macedonian",
  "Norwegian",
  "Omani",
  "Pakistani",
  "Palauan",
  "Palestinian",
  "Panamanian",
  "Papua New Guinean",
  "Paraguayan",
  "Peruvian",
  "Philippine",
  "Polish",
  "Portuguese",
  "Qatari",
  "Romanian",
  "Russian",
  "Rwandan",
  "Saint Kitts and Nevis",
  "Saint Lucian",
  "Saint Vincent and the Grenadines",
  "Salvadoran",
  "Samoan",
  "San Marinese",
  "Sao Tomean",
  "Saudi Arabian",
  "Senegalese",
  "Serbian",
  "Seychellois",
  "Sierra Leonean",
  "Singaporean",
  "Slovak",
  "Slovenian",
  "Solomon Islander",
  "Somali",
  "South African",
  "South Korean",
  "South Sudanese",
  "Spanish",
  "Sri Lankan",
  "Sudanese",
  "Surinamese",
  "Swedish",
  "Swiss",
  "Syrian",
  "Tajik",
  "Tanzanian",
  "Thai",
  "Timorese",
  "Togolese",
  "Tongan",
  "Trinidadian and Tobagonian",
  "Tunisian",
  "Turkish",
  "Turkmen",
  "Tuvaluan",
  "Ugandan",
  "Ukrainian",
  "Uruguayan",
  "Uzbek",
  "Vanuat",
];

export const persons = [
  {
    name: "H.E. OMAR SULTAN ALOLAMA​",
    designation:
      "Minister of State for Artificial Intelligence, Digital Economy and Remote Work Applications",
    company: "UAE Government",
    country: "UAE",
    Image:
      "https://gitex.com/Uploads//Posts/H.E.%20Omar%20Sultan%20AlOlama.jpeg",
  },
  {
    name: "EDGAR PEREZ​",
    designation: "Knightmare on Wall Street",
    company: "Extreme E",
    country: "USA",
    Image: "https://gitex.com/Uploads//Posts/Speakers%202023/Edgar%20Perez.png",
  },
  {
    name: "Alex Genov",
    designation: "Head of Marketing Insights and Customer Research",
    company: "Zappos",
    country: "USA",
    Image: "https://gitex.com/Uploads//Posts/Speakers%202023/Alex%20Genov.png",
  },
  {
    name: "CHRISTINE GZ​",
    designation: "Professional Off-Road and Rally driver",
    company: "Extreme E",
    country: "Spain",
    Image:
      "https://gitex.com/Uploads//Posts/Speakers%202023/Christine%20GZ%E2%80%8B.jpg",
  },
  {
    name: "Amanda Drury",
    designation: "Anchor",
    company: "CNBC",
    country: "Australia",
    Image: "https://gitex.com/Uploads//Posts/Amanda%20Drury.png",
  },
  {
    name: "DR. YANNIS IOANNIDIS President​",
    designation: "Association of Computing Machinery",
    company: "Extreme E",
    country: "Greece",
    Image: "https://gitex.com/Uploads//Posts/Speakers%202023/yannis.jpg",
  },

  {
    name: "GRACY CHEN​",
    designation: "Managing Director",
    company: "Bitget",
    country: "United Kingdom",
    Image: "https://gitex.com/Uploads//Posts/Gracy%20Chen.png",
  },
  {
    name: "BENITO BLANCO",
    designation: "Partner, Architecture and Design",
    company: "David Chipperfield Architects",
    country: "United Kingdom",
    Image:
      "https://gitex.com/Uploads//Posts/%20XVERSE%20ACTIVATION%20PARTNERS/Speakers%202023%20Safa/Benito%20Blanco.png",
  },
];
